name: SDF Validation

on:
  push:
    paths:
    - '**.sdf'
    - '**.world'
  pull_request:
    paths:
    - '**.sdf'
    - '**.world'

  workflow_dispatch:

jobs:
  validate:

    name: Validate SDF files

    runs-on: ubuntu-latest

    env:
      SCHEMA_URL: http://sdformat.org/schemas/root.xsd

    steps:
      - uses: actions/checkout@v2
      - name: Install Required Packages
        run: sudo apt-get install --no-install-recommends -y libxml2-utils fd-find
      - name: Verify Installations
        run: |
          xmllint --version
          fd --version
      - name: Setup xmllint annotations
        uses: korelstar/xmllint-problem-matcher@v1

      - name: Lint SDF files
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: fd -tf -e 'sdf' -e 'world' -X xmllint --schema "$SCHEMA_URL" --noout --load-trace

  # TODO: check formatting of SDF files
