name: SDF Validation

on:
  push:
    paths:
    - '**.sdf'
  pull_request:
    paths:
    - '**.sdf'

  workflow_dispatch:

jobs:
  validate:

    name: Validate SDF files

    runs-on: ubuntu-latest

    env:
      SCHEMA_URL: http://sdformat.org/schemas/root.xsd

    steps:
      - uses: actions/checkout@v2
      - name: Install Required Packages
        run: sudo apt-get install --no-install-recommends -y libxml2-utils
      - name: Setup xmllint annotations
        uses: korelstar/xmllint-problem-matcher@v1

      - name: Lint SDF files
        # ripped from https://github.com/korelstar/xmllint-problem-matcher/blob/26cc4130cb560d39ef1320273f1662ba9182d05f/.github/workflows/lint.yml#L18
        run: fd '.sdf' "$GITHUB_WORKSPACE" -tf -X xmllint --schema "$SCHEMA_URL" --noout

  # TODO: check formatting of SDF files
